Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -22,27 +22,27 @@ runs:
   using: "composite"
   steps:
 
-      - name: "Validate input"
-        shell: bash
-        run: |
-         validate_boolean() {
-           local input=$1
-           local option_name=$2
-           if ! [[ "$input" =~ ^(true|false)$ ]]; then
-             echo "Invalid value for option $option_name. Expected 'true' or 'false', but found '$input'"
-             exit 1;
-            fi
-         }
-
-         validate_mode () {
-          if ! [[ "${{ inputs.mode }}" =~ ^(default|onlyneeded|loadall)$ ]]; then
-            echo "Invalid value for option mode. Expected 'default', 'onlyneeded' or 'loadall' but found '${{ inputs.mode }}'"
+    - name: "Validate input"
+      shell: bash
+      run: |
+        validate_boolean() {
+          local input=$1
+          local option_name=$2
+          if ! [[ "$input" =~ ^(true|false)$ ]]; then
+            echo "Invalid value for option $option_name. Expected 'true' or 'false', but found '$input'"
             exit 1;
-          fi
-         }
+           fi
+        }
 
-         validate_mode
-         validate_boolean "${{ inputs.warnings-as-errors }}" warnings-as-errors
+        validate_mode () {
+         if ! [[ "${{ inputs.mode }}" =~ ^(default|onlyneeded|loadall)$ ]]; then
+           echo "Invalid value for option mode. Expected 'default', 'onlyneeded' or 'loadall' but found '${{ inputs.mode }}'"
+           exit 1;
+         fi
+        }
+
+        validate_mode
+        validate_boolean "${{ inputs.warnings-as-errors }}" warnings-as-errors
   
     - name: "Run GAP test suite"
       shell: bash
